### ISSUE TITLE
network error during installation

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/SourceWindowsInstaller#20]
I received an email from Lian de Jel

with the following torxakis installer error
![lian-tomtom](https://user-images.githubusercontent.com/18348654/32824034-9e0e2f00-c9df-11e7-96e3-5ab62412edb7.png)

Note that the network drives G, H, P and Q are all not available.

**Comment by keremispirli** [comment]
“ftal_cc3.yam” is a temporary name given by our installer tool (WiX) for the TorXakis configuration file “.torxakis.yaml”. This particular file should be in “user home” folder for TorXakis to be able to access it. The installer tries to put this file into “%HOMEDRIVE%%HOMEPATH%”, which I expect to be set to H: in this case. In fact, I could recreate the error by intentionally setting my %HOMEDRIVE% to an unavailable network drive:
![image](https://user-images.githubusercontent.com/661967/32889338-d060c238-caca-11e7-980e-fe38f30e582c.png)

The easiest way to fix this problem is to make the home directory path available during installation (in this case reconnect to network drive H:). There will be no “ftal_cc3.yam” file after the installation, but a “.torxakis.yaml” file will be added to “H:\” directory. This file can be edited to configure TorXakis to use a different solver than default (Z3) solver.

After installation is complete, it is still possible to run TorXakis without access to that file (i.e. even when H: drive is disconnected). That will make TorXakis run with default configuration which uses Z3 solver.

This information is communicated to the user; waiting for response.

**Comment by pjljvandelaar** [comment]
@keremispirli Good work!

I however disagree with the invalid label.
Can we check that the `%HOMEDRIVE%%HOMEPATH%` exists before trying to write this file?

**Comment by keremispirli** [comment]
Currently TorXakis searches for this file in user's home directory, that's why we set installer to write it there. We use OS environment variables to find the path to user's home directory; that directory being unavailable is a local configuration problem of that OS user account, hence the `invalid` label.

It looks like it's possible to skip installing files in certain conditions like existence of a path, but I'm not sure it is a good idea. It will mean we silently complete an installation without proper config file, which will be a hidden problem until the user wants to configure TorXakis.

Using APPDATA or LOCALAPPDATA environment variables to store the configuration file may also be options, but another machine may have their own weird configuration for those environment variables. 

That leaves using the installation directory; which means TorXakis should be updated to read the installation location from Registry.

**Comment by pjljvandelaar** [comment]
I would like a good error message: like `%HOMEDRIVE%%HOMEPATH%` point to `H:`, yet this location doesn't exists.
The user then probably knows what to `repair`

**Comment by keremispirli** [comment]
How about this:
![error box](https://user-images.githubusercontent.com/661967/32950793-f287ac2c-cba7-11e7-9d24-381803171ce4.png)

**Comment by pjljvandelaar** [comment]
Great
